"""Offline fixtures for the only supported pre-v1 updater bridge.

The legacy public layout is recorded from tag v0.2.2 (812a699c), not inferred
from a user's installation.  All fixture secrets and user-authored files are
synthetic.
"""
from __future__ import annotations

import hashlib
import shutil
import zipfile
from pathlib import Path
from types import SimpleNamespace

import pytest

import scripts.update_release as updater


def _digest_tree(root: Path) -> dict[str, str]:
    return {
        str(path.relative_to(root)).replace("\\", "/"): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _v1_release_zip(tmp_path: Path) -> tuple[Path, Path]:
    archive = tmp_path / "PresenceKit-v1.0.0-win64-setup.zip"
    with zipfile.ZipFile(archive, "w") as package:
        package.writestr("VERSION", "v1.0.0\n")
        package.writestr("main.py", "V1_PROGRAM = True\n")
        package.writestr("scripts/update_release.py", "# packaged updater\n")
        package.writestr("bundled/characters/default/card.json", '{"id": "default"}\n')
        package.writestr("bundled/characters/default/traits.yaml", "traits: []\n")
        package.writestr("bundled/seeds/reality/relations.yaml", "relations: []\n")
    checksum = archive.with_suffix(archive.suffix + ".sha256")
    checksum.write_text(f"{updater.sha256_file(archive)}  {archive.name}\n", encoding="utf-8")
    return archive, checksum


def _v0_2_2_installation(tmp_path: Path) -> Path:
    install = tmp_path / "PresenceKit"
    install.mkdir()
    (install / "VERSION").write_text("v0.2.2\n", encoding="utf-8")
    (install / "main.py").write_text("V0_PROGRAM = True\n", encoding="utf-8")

    # Real v0.2.2 release-owned paths, using harmless fake payloads.
    for relative in updater.SUPERSEDED_PUBLIC_ASSETS:
        target = install.joinpath(*relative.parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f"legacy public fixture: {relative}\n", encoding="utf-8")

    # Private/authored and runtime material must never be generated by a release.
    (install / "userdata" / "characters" / "cards").mkdir(parents=True)
    (install / "userdata" / "characters" / "cards" / "private-card.json").write_text(
        '{"id": "private-fixture"}\n', encoding="utf-8"
    )
    (install / "data" / "runtime" / "memory").mkdir(parents=True)
    (install / "data" / "runtime" / "memory" / "fixture.json").write_text(
        '{"memory": "synthetic"}\n', encoding="utf-8"
    )
    (install / "config.yaml").write_text("admin:\n  secret_key: FAKE_CONFIG_SECRET\n", encoding="utf-8")
    (install / "config.local.yaml").write_text("local_override: FAKE_LOCAL_CONFIG\n", encoding="utf-8")
    (install / "secrets.local.yaml").write_text("fixture_token: FAKE_TOKEN_ONLY\n", encoding="utf-8")
    (install / "characters").mkdir(exist_ok=True)
    (install / "characters" / "private-legacy-card.json").write_text("private legacy asset\n", encoding="utf-8")
    (install / "legacy-private-note.bin").write_bytes(b"synthetic unknown legacy private file")
    return install


def _run_offline_update(install: Path, archive: Path, checksum: Path) -> None:
    updater.update(
        install,
        SimpleNamespace(
            source_zip=str(archive), sha256_file=str(checksum), target_version="v1.0.0",
            yes=True, skip_sync=True,
        ),
    )


def test_fresh_v1_fixture_has_bundled_layout_without_bridge_marker(tmp_path):
    archive, _ = _v1_release_zip(tmp_path)
    source = updater.extract_release(archive, tmp_path / "fresh-stage")
    fresh = tmp_path / "fresh-install"
    shutil.copytree(source, fresh)

    assert updater.current_version(fresh) == "v1.0.0"
    assert (fresh / "bundled" / "characters" / "default" / "card.json").is_file()
    assert not updater.bridge_marker_path(fresh).exists()


def test_v0_2_2_bridge_preserves_private_state_and_replaces_only_public_assets(tmp_path, monkeypatch):
    archive, checksum = _v1_release_zip(tmp_path)
    install = _v0_2_2_installation(tmp_path)
    protected_before = {
        name: _digest_tree(install / name)
        for name in ("userdata", "data")
    }
    protected_files_before = {
        name: hashlib.sha256((install / name).read_bytes()).hexdigest()
        for name in ("config.yaml", "config.local.yaml", "secrets.local.yaml")
    }
    monkeypatch.setattr(updater, "_service_is_running", lambda: False)

    _run_offline_update(install, archive, checksum)

    assert updater.bridge_marker_path(install).read_text(encoding="utf-8") == "v0.2.2_to_v1_bridge_completed\n"
    assert (install / "bundled" / "characters" / "default" / "card.json").is_file()
    assert not any((install.joinpath(*path.parts)).exists() for path in updater.SUPERSEDED_PUBLIC_ASSETS)
    assert (install / "characters" / "private-legacy-card.json").read_text(encoding="utf-8") == "private legacy asset\n"
    assert (install / "legacy-private-note.bin").read_bytes() == b"synthetic unknown legacy private file"
    assert protected_before == {name: _digest_tree(install / name) for name in protected_before}
    assert protected_files_before == {
        name: hashlib.sha256((install / name).read_bytes()).hexdigest() for name in protected_files_before
    }
    backup = install / "_update_backup_v0.2.2"
    assert updater.current_version(backup) == "v0.2.2"
    assert _digest_tree(backup / "data") == protected_before["data"]
    assert (backup / "legacy-private-note.bin").read_bytes() == b"synthetic unknown legacy private file"


def test_completed_bridge_can_be_repeated_without_replacing_original_backup(tmp_path, monkeypatch):
    archive, checksum = _v1_release_zip(tmp_path)
    install = _v0_2_2_installation(tmp_path)
    monkeypatch.setattr(updater, "_service_is_running", lambda: False)
    _run_offline_update(install, archive, checksum)
    backup = install / "_update_backup_v0.2.2"
    original_backup_digest = _digest_tree(backup)

    _run_offline_update(install, archive, checksum)

    assert updater.bridge_marker_path(install).is_file()
    assert _digest_tree(backup) == original_backup_digest
    assert (install / "main.py").read_text(encoding="utf-8") == "V1_PROGRAM = True\n"


def test_bridge_failure_leaves_no_marker_and_the_same_command_can_retry(tmp_path, monkeypatch):
    archive, checksum = _v1_release_zip(tmp_path)
    install = _v0_2_2_installation(tmp_path)
    monkeypatch.setattr(updater, "_service_is_running", lambda: False)

    original_bootstrap = updater.run_existing_v1_migration_bootstrap
    monkeypatch.setattr(updater, "run_existing_v1_migration_bootstrap", lambda _: (_ for _ in ()).throw(updater.UpdateError("fixture failure")))
    with pytest.raises(updater.UpdateError, match="fixture failure"):
        _run_offline_update(install, archive, checksum)

    assert not updater.bridge_marker_path(install).exists()
    assert updater.current_version(install) == "v1.0.0"
    assert updater.current_version(install / "_update_backup_v0.2.2") == "v0.2.2"

    monkeypatch.setattr(updater, "run_existing_v1_migration_bootstrap", original_bootstrap)
    _run_offline_update(install, archive, checksum)
    assert updater.bridge_marker_path(install).is_file()


def test_program_copy_failure_is_loud_and_keeps_preupdate_program(tmp_path, monkeypatch):
    archive, checksum = _v1_release_zip(tmp_path)
    install = _v0_2_2_installation(tmp_path)
    monkeypatch.setattr(updater, "_service_is_running", lambda: False)
    original_replace = updater.os.replace
    replace_calls = 0

    def fail_second_replace(source, destination):
        nonlocal replace_calls
        replace_calls += 1
        if replace_calls == 2:
            raise OSError("disk full")
        original_replace(source, destination)

    monkeypatch.setattr(updater.os, "replace", fail_second_replace)

    with pytest.raises(updater.UpdateError, match="程序文件复制失败"):
        _run_offline_update(install, archive, checksum)

    assert updater.current_version(install) == "v0.2.2"
    assert (install / "main.py").read_text(encoding="utf-8") == "V0_PROGRAM = True\n"
    assert updater.current_version(install / "_update_backup_v0.2.2") == "v0.2.2"


def test_manual_restore_returns_the_complete_v0_2_2_snapshot(tmp_path, monkeypatch):
    archive, checksum = _v1_release_zip(tmp_path)
    install = _v0_2_2_installation(tmp_path)
    monkeypatch.setattr(updater, "_service_is_running", lambda: False)
    before = _digest_tree(install)
    _run_offline_update(install, archive, checksum)

    updater.restore_installation_from_backup(install, install / "_update_backup_v0.2.2")

    restored = _digest_tree(install)
    assert updater.current_version(install) == "v0.2.2"
    assert "bundled/characters/default/card.json" not in restored
    assert all(restored[name] == digest for name, digest in before.items())


@pytest.mark.parametrize("source", ["v0.1.5", "unknown", ""])
def test_version_gate_rejects_older_or_unrecognized_sources(tmp_path, source):
    with pytest.raises(updater.UpdateError, match="仅支持 v0.2.2"):
        updater.select_update_mode(tmp_path, source, "v1.0.0")


def test_version_gate_rejects_downgrade(tmp_path):
    with pytest.raises(updater.UpdateError, match="不支持 downgrade"):
        updater.select_update_mode(tmp_path, "v1.0.1", "v1.0.0")
